### ISSUE TITLE
$select query doesn't work

### ISSUE THREAD

**Issue by Roman1991** [AutoMapper/AutoMapper.Extensions.OData#10]
Instead of returning the specified properties from a $select query, GetAsync or GetQueryAsync will return all (selected + unselected) properties.

**Model/Dto:**
```
public class User {

 public int Id { get; set; }
 public string Name { get; set; }
}
```

**OData** select query:
`$select: id`

**GetAsync** method:

`ICollection<User> result = await sourceQueryable.GetAsync(mapper, odataOptions);`

`Output`:

```
{
 Id: 1
 Name: "TestUser"
}
```

**Comment by xaviervv** [comment]
Is a known issue. Reported it as well with the previous issues. Author of package is aware. All dto properties are returned. Look at the issue regarding orderby

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Roman1991** [comment]
Thanks for your reply. Hopefully, the author will be able to fix this soon.

**Comment by xaviervv** [comment]
I was too quick to reply, my bad. 

If you are talking about the json returned by the odata call, then the select should be applied correctly. 

However, EF Core does select all of the fields of the DTO instead of just the selected fields.

**Comment by BlaiseD** [comment]
No we need an implementation for $select to return an anonymous type.  I'll leave this open until it's ready.

**Comment by BlaiseD** [comment]
Should be working using QueryableExtensions.GetQueryAsync in [version 1.0.2-preview04](https://www.nuget.org/packages/AutoMapper.AspNetCore.OData.EFCore/1.0.2-preview04). See the [unit tests](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/master/AutoMapper.OData.EFCore.Tests/GetQuerySelectTests.cs).

**Comment by RobTF** [comment]
Hi,

This doesn't appear to work in the latest version (1.0.5) when the DTO has non-nullable value typed properties on it. These still come through (albeit as their natural "default" value).

**Comment by BlaiseD** [comment]
@RobTF - what you've described should work - see the [tests](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/master/AutoMapper.OData.EFCore.Tests/GetQuerySelectTests.cs).

If not - maybe open an issue with code for the failing scenario.
