### ISSUE TITLE
$select should work for simple properties as well

### ISSUE THREAD

**Issue by MeikelLP** [AutoMapper/AutoMapper.Extensions.OData#110]
According to the [spec](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) $select should work for simple properties, but it does not.

Entities
```json
[{
  "Name": "Test1",
  "Id": "07e61d50-30af-42a6-8aa4-4911509cd742"
},
{
   "Name": "Test2",
   "Id": "3e9b144a-0cd7-4068-b9b3-84ad7d600944"
}]
```

Query
```
?$select=Name
```

## Expected Result

```json
[{
   "Name": "Test1"
},
{
   "Name": "Test2"
}]
```

## Actual Result

```json
[{
  "Name": "Test1",
  "Id": "07e61d50-30af-42a6-8aa4-4911509cd742"
},
{
   "Name": "Test2",
   "Id": "3e9b144a-0cd7-4068-b9b3-84ad7d600944"
}]
```

**Comment by BlaiseD** [comment]
Pretty sure you can do that with this library.  The following is from one of the sample applications:

![image](https://user-images.githubusercontent.com/7595209/133457969-8565ffd3-913e-49f4-9fe4-c9fc2f0437cb.png)

**Comment by MeikelLP** [comment]
Here I got a working repository:
https://github.com/MeikelLP/automapper-odata-bug

This happened in 2 projects (private and in-company) and this triggers me now that hard that I created a sample for you :D

![image](https://user-images.githubusercontent.com/11669846/133852523-7825cf76-a827-495f-969f-fc153a81f001.png)

**Comment by BlaiseD** [comment]
Your configuration  has not been setup with [explicit expansion](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/c196308e7c15c1ed82653c60e396fce2df4fa076/WebAPI.OData.EFCore/Mappings/CoreBuildingMappings.cs#L13) - that's probably the difference.

**Comment by MeikelLP** [comment]
So by design I must make all props expandable or else select will not work? Isn't that kind of intuitive?

**Comment by MeikelLP** [comment]
I added ExplicitExpansion but it still does not work.

**Comment by BlaiseD** [comment]
> So by design I must make all props expandable or else select will not work? Isn't that kind of unintuitive?

PRs are welcome for a different approach.

**Comment by BlaiseD** [comment]
Issues are really for bugs you've discovered in the library.  I would start with the working [sample applications](https://github.com/AutoMapper/AutoMapper.Extensions.OData/tree/master/WebAPI.OData.EFCore) or the [tests](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/master/AutoMapper.OData.EFCore.Tests/GetQuerySelectTests.cs) and figure it out from there.

**Comment by FramingApp** [comment]
> Issues are really for bugs you've discovered in the library. I would start with the working [sample applications](https://github.com/AutoMapper/AutoMapper.Extensions.OData/tree/master/WebAPI.OData.EFCore) or the [tests](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/master/AutoMapper.OData.EFCore.Tests/GetQuerySelectTests.cs) and figure it out from there.

Ok, Bug: ExplicitExpansion doesnt do anything

**Comment by BlaiseD** [comment]
I think the [tests](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/1a19647bb351f2889a5706cbe1f8bd72e6fde378/AutoMapper.OData.EFCore.Tests/GetQueryTests.cs#L150) say otherwise.
