### ISSUE TITLE
Support for Custom Value resolvers.

### ISSUE THREAD

**Issue by YRCristiPagu** [AutoMapper/AutoMapper.Extensions.OData#116]
Hi,

I have a custom value resolver used in my map and when I try to make a call with GetQueryAsync I get a timeout. If I replace the custom value resolver on the property with an Ignore() then the query works. 
Is the custom value resolver not supported?

**Comment by BlaiseD** [comment]
You're probably correct.  The relevant [code is here](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/1a19647bb351f2889a5706cbe1f8bd72e6fde378/AutoMapper.AspNetCore.OData.EFCore/QueryableExtensions.cs#L202).

Expression mapping does not use custom resolvers.  Not sure if `ProjectTo` does either. You should be able to confirm by testing your configuration against `MapExpression` and `ProjectTo`.

**Comment by YRCristiPagu** [comment]
Hi Blaise,
Thank you for your response!
I can confirm this is not supported. I found also in the AutoMapper documentation that the value resolvers are not supported for IQueryable extensions (see [here](https://docs.automapper.org/en/stable/Queryable-Extensions.html#supported-mapping-options)).
Do you have any ideas of workarounds?
For now the current setup is that we have a DbSet from a view. There is a one to many relationship with another view, but that is not possible to set up in entity, because you cannot have a foreign key to a view. We have a Member Value Resolver that 
maps the elements from that makes a separate request to get the related entity and map it to the property.
We need to support filtering on that property.

**Comment by BlaiseD** [comment]
Best to create a [sample repository](https://github.com/YRCristiPagu?tab=repositories) demonstrating the problem.  That will make it easier to  determine either way.
