### ISSUE TITLE
Queryable extensions ignore the $search clause 

### ISSUE THREAD

**Issue by rdelmont** [AutoMapper/AutoMapper.Extensions.OData#118]
Using AspnetCore.OData 8.0.6, I defined a SearchBinder to support $search implementation. But this options is ignored by the Queryable extension. 
The only way to make it do something is to use EnableQuery which is not recommended. In fact things go wild when using both EnableQuery and Queryable extension so it's not a viable solution.

**Comment by trojanmartin** [comment]
Search is new query option added in last release of the OData. AutoMapper.Extensions.OData is currently ignoring it. I will try to create a PR with this feature implemented in few days.

**Comment by BlaiseD** [comment]
That is correct.  PRs are welcome for missing features.
