### ISSUE TITLE
OData $select query not working

### ISSUE THREAD

**Issue by Schinwinkwinsky** [AutoMapper/AutoMapper.Extensions.OData#147]
Hello, everybody

Working with this extension I have noticed that OData $select query is not working with it. I have tested with: $top, $skip, $select, $expand, $filter and $orderBy. All kind of queries are working great, but $select.

![image](https://user-images.githubusercontent.com/13337108/185200788-86f58c5d-3fa4-443b-8332-9bf61ed890eb.png)

**Comment by BlaiseD** [comment]
There are [tests here](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/8b5d4896adc9404ea7ec581826b3327665062b15/AutoMapper.OData.EFCore.Tests/GetQuerySelectTests.cs#L61)e using `$select` - maybe compare those with your configuration.

**Comment by Schinwinkwinsky** [comment]
I could see some differences. I set up my project using OData documentation. And it's like that:

```
using MediatR;
using Microsoft.AspNetCore.OData;
using Microsoft.EntityFrameworkCore;
using School.Data;
using School.Domain;
using School.WebAPI.Other;
using System.Reflection;
using System.Text.Json.Serialization;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers()
    .AddOData()
    .AddJsonOptions(options => options.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles);

```
But on your tests, OData is added on an IMvcCoreBuilder.

```
private void Initialize()
{
    IServiceCollection services = new ServiceCollection();
    IMvcCoreBuilder builder = new TestMvcCoreBuilder
    {
        Services = services
    };

    builder.AddOData();
```

I noticed that in your tests, you use OData v8.0.6. So I reverted to that version in my project and the result was the same. 
If you could test on my project, it's available on https://github.com/Schinwinkwinsky/School. I'd really appreciate your help.

**Comment by BlaiseD** [comment]
It's probably better if you reproduce your failing case using the tests from this library - there are [web tests](https://github.com/AutoMapper/AutoMapper.Extensions.OData/tree/master/Web.Tests) calling controllers as well as [tests creating the EDM mode](https://github.com/AutoMapper/AutoMapper.Extensions.OData/tree/master/AutoMapper.OData.EFCore.Tests)l without the controller.

You're probably just missing an explicit expansion in your configuration e.g. compare the profiles [here](https://github.com/AutoMapper/AutoMapper.Extensions.OData/tree/master/WebAPI.OData.EFCore/Mappings) to yours.

**Comment by Schinwinkwinsky** [comment]
Ok, I think I got it. I set up profile as your tests:

Before:
![image](https://user-images.githubusercontent.com/13337108/185498231-7040e28c-44f7-4fdb-8796-20388f6fa38d.png)

After:
![image](https://user-images.githubusercontent.com/13337108/185498345-4e62e407-26b3-4da7-bf2c-2924b30bc04e.png)

The result is that when we query with $select, the properties not selected come with null or default value.
![image](https://user-images.githubusercontent.com/13337108/185498750-9df3fdde-9807-41c1-86e2-e5105ca10362.png)

I think that's why all tests are ok. I don't know if it's a normal behavior, but when I use $select without AutoMapper, the properties not selected just didn't come when requested. It was not the result I expected. 
I'm not sure, but I thought ExplicitExpansion is to use with $expand query. Sorry, I'm new with OData and AutoMapper. Thank you for your help.

**Comment by BlaiseD** [comment]
Yep - not sure what the difference is with other libraries.  We project to the `TModel` and return it.

![image](https://user-images.githubusercontent.com/7595209/185612283-4a4d4020-6427-4a7e-aede-6b5bbb43547f.png)

PRs are welcome for any improvement.

**Comment by BlaiseD** [comment]
With regard to explicit expansion, literal types are expanded by default unless a $select is specified.  All members are eligible for expansion - not just navigation properties.

**Comment by Schinwinkwinsky** [comment]
Thank you very much! I'm gonna study more and try to submit a PR.
