### ISSUE TITLE
Exception when filtering on many to many

### ISSUE THREAD

**Issue by AlbertoBonfiglio** [AutoMapper/AutoMapper.Extensions.OData#15]
Hi,
I am not sure if it's an issue with my code or the library.
I have a model that has several one to many and one many to many navigation properties

When filtering on the one to many I get the expected results. However if I try filtering on the many to many I get an exception,
This is my query: 
https://localhost:5001/api/incidents?$expand=personType, location, incidentType, eventTypes & $filter=deleted eq false and location/name eq 'MHC' or eventTypes/any(e:e/id eq d98d3c8e-6951-402f-ab3d-c2fcedc24171)

This is the mapping
```
 CreateMap<Report, ReportDTO>()
            .ForMember(dto => dto.EventTypes, opt => opt
                .MapFrom(src => src.IncidentEventTypes.Select(i => i.EventType).ToList())
            );
            
           CreateMap<ReportDTO, Report>()
            // this is to prevent actions to be submitted up
            .ForMember(d => d.Location, opt => opt.Ignore())
            .ForMember(d => d.PersonType, opt => opt.Ignore())
            .ForMember(d => d.IncidentType, opt => opt.Ignore())
            .ForMember(d => d.LocationId, opt => opt.MapFrom(src => src.Location.Id))
            .ForMember(d => d.PersonTypeId, opt => opt.MapFrom(src => src.PersonType.Id))
            .ForMember(d => d.IncidentTypeId, opt => opt.MapFrom(src => src.IncidentType.Id))
            .ForMember(d => d.IncidentEventTypes, opt => opt
                .MapFrom((src, dst) => src.EventTypes
                    .Select(eventType => 
                        new IncidentEventType() {ReportId = dst.Id, EventTypeId = eventType.Id })
                    .ToList()
                )
            )
            .ForMember(d => d.CreatedDate, opt => opt.Ignore())
            .EqualityComparison((odto, o) => odto.Id == o.Id);

```

this is the exception:
"Expression of type 'System.Collections.Generic.List`1[Benton.HealthIR.Models.EventType]' cannot be used for parameter of type 'System.Linq.IQueryable`1[Benton.HealthIR.Models.EventType]' of method 'Boolean Any[EventType](System.Linq.IQueryable`1[Benton.HealthIR.Models.EventType], System.Linq.Expressions.Expression`1[System.Func`2[Benton.HealthIR.Models.EventType,System.Boolean]])' (Parameter 'arg0')"

this is the stack:
"   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)\r\n   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1)\r\n   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EnumerableToQueryableMethodConvertingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)\r\n   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)\r\n   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)\r\n   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)\r\n   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)\r\n   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)\r\n   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)\r\n   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)\r\n   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)\r\n   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)\r\n   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)\r\n   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)\r\n   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)\r\n   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)\r\n   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.IncludableQueryable`2.GetAsyncEnumerator(CancellationToken cancellationToken)\r\n   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()\r\n   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)\r\n   at AutoMapper.AspNet.OData.QueryableExtensions.GetAsync[TModel,TData](IQueryable`1 query, IMapper mapper, Expression`1 filter, Expression`1 queryFunc, ICollection`1 includeProperties)\r\n   at AutoMapper.AspNet.OData.QueryableExtensions.GetAsync[TModel,TData](IQueryable`1 query, IMapper mapper, ODataQueryOptions`1 options, HandleNullPropagationOption handleNullPropagation)\r\n   at Benton.HealthIR.API.Controllers.IncidentsController.GetIncidents(ODataQueryOptions`1 options, Boolean restrict) in C:\\Repos\\HealthIR-Odata\\HealthIR\\API\\Controllers\\IncidentController.cs:line 71"

I think it has to do with the mapping but i am not certain. Any help is greatly appreciated

**Comment by BlaiseD** [comment]
I would download the code and put a breakpoint [here](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/45371f93c8928795befc6f32d9ee8f17881ca9e8/AutoMapper.AspNetCore.OData.EFCore/QueryableExtensions.cs#L106) and see if the expressions are as expected. 

If that doesn't clear it up you can post a failing sample to a [repo](https://github.com/AlbertoBonfiglio?tab=repositories).

**Comment by AlbertoBonfiglio** [comment]
Will do! Thanks!!

**Comment by AlbertoBonfiglio** [comment]
Hi,
I solved one issue. Apparently the problem was with my mappings calling a toList(). Once i removed that from the mapping that error disappeared but another popped up: "EF.Property called with wrong property name.
https://localhost:5001/api/incidents?$expand=location, eventTypes & $filter= eventTypes/any(e:e/name eq 'Medical Alert')

My model looks like this:
 {
            "id": "dd23084c-04d8-40d5-c542-08d7cd271701",
            "employeeId": "xxxx",
            "firstName": "xxxx",
            "lastName": "xxxx",
            "date": "2020-03-16T07:00:00Z",
            "mrn": "sss",
            "phoneNumber": "ss",
            "content": "Testsss   jjjjj",
            "createdDate": "2020-03-20T23:33:27.106794Z",
            "finalized": false,
            "status": 0,
            "deleted": false,
            "location": {
                "id": "7964b58b-099e-4a73-9d61-c6b5a871720a",
                "name": "MHC",
                "description": "",
                "deleted": false
            },
            "eventTypes": [
                {
                    "id": "d98d3c8e-6951-402f-ab3d-c2fcedc24171",
                    "name": "Medical Alert",
                    "description": "",
                    "deleted": false
                },
                {
                    "id": "eaa802b9-7e2f-4439-bc0c-86ad495f0de5",
                    "name": "Medication Error",
                    "description": "",
                    "deleted": false
                }
            ]
        }

**Comment by BlaiseD** [comment]
You'll have to put up a [repo](https://github.com/AlbertoBonfiglio?tab=repositories) where we can see it fail.

**Comment by AlbertoBonfiglio** [comment]
Hi, here's the repo 
https://github.com/AlbertoBonfiglio/AutomapperOdata/tree/master/HealthIR

this works https://localhost:5001/api/incidents?$expand=location, eventTypes & $filter= location/name eq 'MHC' 

this doesn't 
https://localhost:5001/api/incidents?$expand=location, eventTypes & $filter= eventTypes/any(e:e/name eq 'Medical Alert')

NB when you first run the app the eventtype collection is empty for all objects.  In my dataset they are not but it shouldn't make a difference for debugging.

I appreciate your help immensely!

**Comment by BlaiseD** [comment]
The mapping looks correct.  You may want to post a question to the [EF Core Repo](https://github.com/dotnet/efcore) - I see a similar [issue has been posted](https://github.com/dotnet/efcore/issues/19155) before.

However, disabling null checks does simplify the filter expression: `return Ok(await query.GetAsync(_mapper, options, HandleNullPropagationOption.False));` - which does not throw the exception.

### With null handling:
```c#
            Expression<Func<ReportDTO, bool>> filterNullHandling = it => 
            (
                IIF
                (
                    (it.EventTypes == null),
                    null,
                    Convert
                    (
                        it.EventTypes.Any
                        (
                            e => 
                                (
                                    IIF((e == null), null, e.Name)  
                                    ==  
                                    value(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer + TypedLinqParameterContainer`1[System.String]).TypedProperty
                                )
                        ), Nullable`1
                    )
                ) == True
            );
```
maps to:
```c#
            Expression<Func<Report, bool>> filterMappedNullHandling = it => 
            (
                IIF
                (
                    (it.IncidentEventTypes.Select(i => i.EventType) == null),
                    null, 
                    Convert
                    (
                        it.IncidentEventTypes.Select(i => i.EventType).Any
                        (
                            e => 
                            (
                                IIF((e == null), null, e.Name) 
                                == 
                                value(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer + TypedLinqParameterContainer`1[System.String]).TypedProperty
                            )
                        ), Nullable`1
                    )
                ) == True
            );
```

### Without null handling:
```c#
            Expression<Func<ReportDTO, bool>> filter = it => it.EventTypes.Any
            (
                e => 
                (
                    e.Name 
                    == 
                    value(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer + TypedLinqParameterContainer`1[System.String]).TypedProperty
                )
            );
```
maps to:
```c#
            Expression<Func<Report, bool>> filterMapped = it => it.IncidentEventTypes
                    .Select(i => i.EventType)
                    .Any
                    (
                        e => 
                        (
                            e.Name 
                            == 
                            value(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer + TypedLinqParameterContainer`1[System.String]).TypedProperty
                        )
                    );
```

In both cases to conversions look correct.  It looks to me as if EF Core doesn't like the more complex expression.

**Comment by DarthBert** [comment]
Thank you!!
