### ISSUE TITLE
$skip not working

### ISSUE THREAD

**Issue by kristijanmihaljinac** [AutoMapper/AutoMapper.Extensions.OData#16]
I'm using: 
ASP.NET Core 3.1
AutoMapper (9.0.0)
AutoMapper.AspNetCore.OData.EFCore (1.0.1)
Microsoft.AspNetCore.OData (7.4.0-beta) with endpoint routing / non-Edm Approach (https://devblogs.microsoft.com/odata/enabling-endpoint-routing-in-odata/)

This is my request: 
https://localhost:44304/api/domena?$skip=2

and this is query to database: 
SELECT [d].[ID], [d].[AKTIVNA], [d].[NADREDENA_ID], [d].[NAPOMENA], [d].[NAZIV], [d].[OZNAKA], [d].[TIP], [d].[VRSTA]
FROM [DOMENA] AS [d]

This is implementation: 

`_context.Set<TEntity>().AsNoTracking().GetAsync(Mapper, options)`

where options are ODataQueryOptions<TModelListData> options. 
Please help.

**Comment by xaviervv** [comment]
They will ask for a small repository in order to reproduce your result.

I can already tell you that there are no issues regarding skip / top. Already used this library extensively in the past months for another project.

**Comment by kristijanmihaljinac** [comment]
This is my startup config:

`services.AddOData();
 services.AddControllers()
                .AddFluentValidation()
                .AddNewtonsoftJson();

 var mappingConfig = new MapperConfiguration(mc =>
            {
                mc.AddProfile(new MappingProfile());
            });




            IMapper mapper = mappingConfig.CreateMapper();
            services.AddSingleton(mapper);


   services.AddMvcCore(op =>
             {
                    foreach (var formatter in op.OutputFormatters.OfType<ODataOutputFormatter>().Where(it => it.SupportedMediaTypes.Count == 0))
                        formatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/odata"));

                    foreach (var formatter in op.InputFormatters.OfType<ODataInputFormatter>().Where(it => it.SupportedMediaTypes.Count == 0))
                        formatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/odata"));
             });

`

and  Configure(IApplicationBuilder app, IWebHostEnvironment env) are:

`
    app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.Count().Filter().OrderBy().Expand().Select().MaxTop(null).SkipToken(); 
                endpoints.EnableDependencyInjection();

            });

`

**Comment by BlaiseD** [comment]
The library does not support the `$skip` without '$orderby' which I think is consistent with EF Core and EF 6.  See examples in the [tests](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/master/AutoMapper.OData.EFCore.Tests/AllTests.cs).

**Comment by kristijanmihaljinac** [comment]
Thanks. '$orderby' solved my problem.
