### ISSUE TITLE
Improve handling of Enumerations in subqueries

### ISSUE THREAD

**Issue by wbuck** [AutoMapper/AutoMapper.Extensions.OData#170]
Currently `enum`'s in subqueries are handled by first converting the `enum` to its underlying `integer` value and then converting that `integer` value to a `string`. This implies that the user is storing the underlying `integer` `enum` value as `string`'s in the backing store.

I believe this ignores the two main use cases of how people actually store `enum`'s in the backing store. 
Those two main use cases are:

1. Storing `enum`'s as `int`'s in the backing store
2. Storing `enum` variants name as `string`'s in the backing store.

The following query:

    SomeEntities($filter=SomeEnumProp eq 'SomeEnumVariant')

Produces the following expression:

    SomeEntitites.Where($it => Convert($It.SomeEnumProp).ToString() == "SomeEnumVariant")

This, I believe is incorrect. 
Entity Framework handles such a query by converting both the member access and the constant to the underlying `enum` `integer` value and then performing the comparison:

     SomeEntitites.Where($it => Convert($It.SomeEnumProp) == 1)

This I believe is the correct way to handle `enum`'s.
This would also allow the user to store the `enum`'s as `string`'s in the backing store as the user of the `API` could `cast` the value prior to performing the binary comparison:

     SomeEntities($filter=cast(SomeEnumProp, Edm.String) eq 'SomeEnumVariant')

Which produces:

    SomeEntities.Where($it => $it.SomeEnumProp.ToString() eq "SomeEnumVariant")

**Comment by BlaiseD** [comment]
Changing this [mapping configuration](https://github.com/BlaiseD/LogicBuilder.Samples/blob/08f2db9f70557afa5612248ba31e4028c8346449/Xamarin/Contoso/Contoso.BSL.AutoMapperProfiles/SchoolProfile.cs#L60) to `opts => opts.MapFrom(x => x.Grade.ToString())` will cause [this test](https://github.com/BlaiseD/LogicBuilder.Samples/blob/08f2db9f70557afa5612248ba31e4028c8346449/Xamarin/Contoso/Contoso.Bsl.Flow.Integration.Tests/ProjectionOperationsTest.cs#L295) to fail.

Unless I'm mistaken the [OData repo](https://github.com/OData/AspNetCoreOData) uses similar logic to ours for handling enums. 

I think the operations are still granular enough to handle a cast from the request where it's possible.

**Comment by wbuck** [comment]
Why would you expected `opts => opts.MapFrom(x => x.Grade.ToString())` to succeed here if the backing store is storing the `enumerations` as `integers`?

I'd like to understand how this:

    Convert(SomeEnumValue).ToString() == "123" 

Is the correct course of action here?
How often do folks store an underlying `enum` value (`int`) as `string`'s in their DB?

It's also not what `ApplyTo` does when dealing with `enum`'s, so I do not believe this is what the Odata repo is doing.

I would expect the same expression whether it's a sub query or not.
The `ApplyTo` function produces the following:

    Convert(SomeEnumValue) == 123;

This is expected.

**Comment by BlaiseD** [comment]
I would have started with.  `RootQuery`\`ApplyTo` behaves differently from subqueries.
e.g.  RootQuery: SomeString,  QueryWithSubQuery: OtherString.

Here are the different results.  Ok to create a new simplified issue if you're interested.

I've updated the issue template.

**Comment by wbuck** [comment]
@BlaiseD OK I've created a new issue. I'm hoping it'll be a bit more clear the issue I was seeing.
