### ISSUE TITLE
Handle of max top in query

### ISSUE THREAD

**Issue by andreamorello93** [AutoMapper/AutoMapper.Extensions.OData#177]
i'm trying to figure out how to handle MaxTop in sql query that is handled in EnableQuery Attribute in standard configuration:

my controller:

[BaseODataDTOController.cs](https://github.com/andreamorello93/ODataExample/blob/8aea3ea01743660f35f53b1db3dee57127620713/src/ODataExample.Api/ODataExample.Api/Controllers/BaseODataDTOController.cs)

Generated SQL query for request: https://localhost:44393/odata/product

`SELECT [p].[ProductID] AS [ProductId]
FROM [Production].[Product] AS [p]`

As you can se there's no top in sql statement. how can i fix this?

**Comment by leoerlandsson** [comment]
Hi,

Setting a PageSize before running the query will generate a TOP statement:

querySettings.ODataSettings.PageSize


public async Task<IEnumerable<TDTO>> Get([SwaggerHide] ODataQueryOptions<TDTO> options)
            => (await _repository.Queryable().GetQueryAsync(_mapper, options, querySettings));



Br,
Leo

**Comment by andreamorello93** [comment]
Thank you Leo!
