### ISSUE TITLE
Enums mapping not work in GetQuery

### ISSUE THREAD

**Issue by petrkasnal** [AutoMapper/AutoMapper.Extensions.OData#181]
Hi,

i use odata automapper extension.

`var items = (_repository.GetAll().GetQuery(_mapper, request.Query)).ToList();`
Everything working fine, but when i add enum to source and destination it not working. I give this error. I have Mapper on enums.

'Unable to create a map expression from Bom.CheckStateType (System.Nullable1[StateType]) to Nullable1.StateType (System.Nullable`1[StateType])'

**Comment by BlaiseD** [comment]
A sample reproducing the error would help. 

Testing your configuration against `ProjectTo` without this library - may reproduce the same error.

**Comment by BlaiseD** [comment]
You're probably missing a `ForMember` in your config telling it how the conversion should work.  Otherwise I would first reference the [main project](https://github.com/AutoMapper/AutoMapper) and pinpoint the cause.  Then create a new issue if it looks like a bug - and post the repro.
