### ISSUE TITLE
Update dependency LogicBuilder.Expressions.Utils

### ISSUE THREAD

**Issue by matthewtquinn1** [AutoMapper/AutoMapper.Extensions.OData#186]
## The issue
This library relies on `LogicBuilder.Expressions.Utils v5.0.6` which relies on `System.Linq.Dynamic.Core v1.2.14`.

## Why is this an issue?
`System.Linq.Dynamic.Core` contains a severe vulnerability in version `1.2.14`.

## What is LogicBuilder.Expressions.Utils doing about it?
They updated the dependency to a safer version as seen in [this commit](https://github.com/BlaiseD/LogicBuilder.DataComponents/commit/bf2ba0447c6b9afa46cc72aeb40e3961edefee77). 

## What can do?
We should update `LogicBuilder.Expressions.Utils` to `5.0.10` (fixed in 5.0.9, but better to get latest patch) to get the fix.

**Comment by matthewtquinn1** [comment]
@BlaiseD I'm happy to create a pull request for this fix if you can add me as a contributor? :)

**Comment by BlaiseD** [comment]
I think you become a [contributor](https://github.com/AutoMapper/AutoMapper.Extensions.OData/graphs/contributors) once your PR gets merged.  PRs welcome.

**Comment by matthewtquinn1** [comment]
@BlaiseD Can you allow me to push my branch please? :)

**Comment by BlaiseD** [comment]
I believe the usual approach is to create the PR from a fork.  GitHub has instructions if you search for the following "Creating a pull request from a fork".

**Comment by matthewtquinn1** [comment]
@BlaiseD  Done now and PR created thanks. 

Would prefer not to have the extra dependency installed locally for us to manage :)
