### ISSUE TITLE
$select is not applied

### ISSUE THREAD

**Issue by DJHightower77** [AutoMapper/AutoMapper.Extensions.OData#189]
Using "$select=id,name" will not return only those two properties but the complete (mapped) entity.

**Comment by BlaiseD** [comment]
You're probably missing explicit expansion in your configuration.  See the [ReadMe](https://github.com/AutoMapper/AutoMapper.Extensions.OData#readme).  Also see working examples in [the tests](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/master/AutoMapper.OData.EFCore.Tests/GetQuerySelectTests.cs).
