### ISSUE TITLE
Not quite sure about the term, different parent child structure

### ISSUE THREAD

**Issue by xaviervv** [AutoMapper/AutoMapper.Extensions.OData#19]
I don't think this is actually a bug. But more of a limitation, unless I am doing something wrong. 

This is my viewmodel
`public class SchedulerEvent : BaseSchedulerViewModel
    {
        public ScheduleEventType EventType { get; set; }
        public List<ScheduleEventTypeMetadata> Metadata { get; set; }
    }

    public class ScheduleEventType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public bool CanWrite { get; set; }
    }

    public class ScheduleEventTypeMetadata
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public List<ScheduleEventTypeMetadataValue> Values { get; set; }
    }

    public class ScheduleEventTypeMetadataValue
    {
        public long Id { get; set; }
        public string Value { get; set; }
    }`

DB side the structure is as follows
EventType has 1+ Metadata has 1+ Values
Event has 1 eventtype, and 1+ EventValues (joining table with ids from metadata, value and event)

PROBLEM: on viewmodel the event.metadata.values need to be filled in from the event.values, as you can see, this is a different hierachy. 

For the mapping profile I would use
`CreateMap<Events.Domain.PlannedEvent, SchedulerEvent>().ForMember(d => d.Metadata, o => o.MapFrom(s => s.EventType.Metadata))
`
But then the viewmodel's metadata.values contains all data from EventType.Metadata.Values instead of PlannedEvent.Values
I don't have access to the PlannedEvent in the CreateMap for metadata, only to metadata.

I tried using an overload of mapfrom so I would have access to the parent. The values property is now filled in from PlannedEvent.Values, and I declared a map for that as well.
`.ForMember(d => d.Metadata, o => o.MapFrom((plannedEvent, schedulerEvent, i, context) =>
                {
                    return plannedEvent.EventType.Metadata.Select(m => new ScheduleEventTypeMetadata
                    {
                        Id = m.MetadataId,
                        Title = m.Metadata.Title,
                        Values = context.Mapper.Map<List<ScheduleEventTypeMetadataValue>>(plannedEvent.PlannedEventValues)
                    });
                }))`

This fails with a collection cannot be null sort of error. Which it isn't. I made sure that even if it's null, a new one was created on initialization.
I expect that something is going wrong with the translation of the expressions. I am not sure if a manual include would fix this, but i've had issues with manually including on the context with odata

Would a configuration like this be supported with this library?

**Comment by BlaiseD** [comment]
Sounds like maybe you need the following if I understand you:
```c#
CreateMap<Events.Domain.PlannedEvent, SchedulerEvent>()
   .ForMember(d => d.Metadata, o => o.MapFrom(s => s.EventType.Metadata.SelectMany(o => o)));
```
You could try `IMapper.Map<ource, dest>(source)`, see if that works first.

**Comment by xaviervv** [comment]
That would be the same result, which is the wrong one. I will provide more context when I am on my laptop.

The values for metadata on the viewmodel, are not the same as the one on the domain.

Domain: plannedeevent.values (navigation to metadata values) contains only the values that were selected for the event.

PlannedEvent.EventType.Metadata.values contain every single value for a metadata.

Viewmodel should have the entity type, some info about metadata (the collection), and all of the related values coming from plannedevent.values.
This is the issue. Metadata does not know anything about the selected values of the planned event.

Only planned event knows. Which is why I was trying to use the override so Icould still access properties of the plannedevent to link the values.

A quick fix would be to change the value viewmodel, add the metadataid to it. And unnest the collection and put it on the root viewmodel.

I could go with that, but I would still like to know of ot was possible or not.

Maybe it isn't clear atm. If so I will provide a small project with the relevant classes or a similar scenario





Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by BlaiseD** [comment]
f Mapper.Map is giving you the same unexpected result then it's likely a configuration problem - yes posting a runnable sample will make it clearer.
