### ISSUE TITLE
Support for discriminators/TPH 

### ISSUE THREAD

**Issue by lenardchristopher** [AutoMapper/AutoMapper.Extensions.OData#198]
Is there support for [Descriminators/TPH](https://learn.microsoft.com/en-us/ef/core/modeling/inheritance#table-per-hierarchy-and-discriminator-configuration)? When I use an OData query without AutoMapper/ODataQueryOptions, I get back `@odata.type` for my inherited entities. After I switched the DTOs, the responses didn't include type info anymore. Is this a limitation or something I'm doing wrong?

### Source/destination types

```csharp
[JsonPolymorphic(UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FailSerialization)]
[JsonDerivedType(typeof(RegistrationDTO), "base")]
[JsonDerivedType(typeof(BarnRegistrationDTO), "barn")]
[JsonDerivedType(typeof(EntryRegistrationDTO), "entry")]
public class RegistrationDTO
{
    [Key]
    public Guid RegistrationId { get; set; }

    public HumanDTO Trainer { get; set; }

    public CompetitionDTO Competition { get; set; }
}

public class BarnRegistrationDTO : RegistrationDTO
{
    public required string Name { get; set; }
}

public class EntryRegistrationDTO : RegistrationDTO
{
    public HumanDTO Owner { get; set; }
}
```

### Mapping configuration

```csharp
        CreateMap<Registration, RegistrationDTO>()
            .ForAllMembers(x => x.ExplicitExpansion());

        CreateMap<BarnRegistration, BarnRegistrationDTO>()
            .IncludeBase<Registration, RegistrationDTO>()
            .ForAllMembers(x => x.ExplicitExpansion());

        CreateMap<EntryRegistration, EntryRegistrationDTO>()
            .IncludeBase<Registration, RegistrationDTO>()
            .ForAllMembers(x => x.ExplicitExpansion());
```

### Version: x.y.z
- AutoMapper.AspNetCore.OData.EFCore 4.0.1
- AutoMapper.Extensions.Microsoft.DependencyInjection 12.0.1
- Microsoft.AspNetCore.OData 8.2.3

### Expected behavior

```json
{
    "@odata.context": "http://localhost:5155/odata/$metadata#Registrations",
    "value": [
        {
            "@odata.type": "#NS.BarnRegistration",
            "registrationId": "4e09e3b5-accb-4d76-43bd-08dbedbf2aac"
        },
        {
            "@odata.type": "#NS.EntryRegistration",
            "registrationId": "b0175d98-9ed8-431d-43be-08dbedbf2aac",
        }
    ]
}
```

### Actual behavior

`http://localhost:5155/odata/Registrations`
```json
{
    "@odata.context": "http://localhost:5155/odata/$metadata#Registrations",
    "value": [
        {
            "registrationId": "4e09e3b5-accb-4d76-43bd-08dbedbf2aac"
        },
        {
            "registrationId": "b0175d98-9ed8-431d-43be-08dbedbf2aac"
        }
    ]
}
```

### Steps to reproduce

RegistrationsController
```csharp
    [HttpGet]
    public async Task<ActionResult> Get(ODataQueryOptions<RegistrationDTO> options)
    {
        return Ok(await _context.Registrations.GetQueryAsync(_mapper, options));
    }
```

EDMModel
```csharp
modelBuilder.EntitySet<RegistrationDTO>("Registrations");
```

**Comment by lenardchristopher** [comment]
I actually found a workaround, thought I don't really understand the underlying logic of why it works. The second comment in [this SO post](https://stackoverflow.com/a/31225649/3501332) led me to it.

My models became
```csharp
[JsonPolymorphic(UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FailSerialization)]
[JsonDerivedType(typeof(BaseRegistrationDTO), "base")]
[JsonDerivedType(typeof(RegistrationDTO), "general")]
[JsonDerivedType(typeof(BarnRegistrationDTO), "barn")]
[JsonDerivedType(typeof(EntryRegistrationDTO), "entry")]
public class BaseRegistrationDTO
{
    [Key]
    public Guid RegistrationId { get; set; }

    public HumanDTO Trainer { get; set; }

    public CompetitionDTO Competition { get; set; }
}

public class RegistrationDTO : BaseRegistrationDTO
{
}

public class BarnRegistrationDTO : RegistrationDTO
{
    public required string Name { get; set; }
}

public class EntryRegistrationDTO : RegistrationDTO
{
    public HumanDTO Owner { get; set; }
}
```
In the above, `RegistrationDTO` renamed => `BaseRegistrationDTO`. Newly created `RegistratioDTO` is empty and inherits from `BaseRegistrationDTO`.

My EDM model became
```csharp
modelBuilder.EntitySet<BaseRegistrationDTO>("Registrations");
modelBuilder.Ignore(typeof(BaseRegistrationDTO));
```

The output now looks like
```json
{
    "@odata.context": "http://localhost:5155/odata/$metadata#Registrations/NS.RegistrationDTO",
    "value": [
        {
            "@odata.type": "#NS.RegistrationDTO",
            "registrationId": "4e09e3b5-accb-4d76-43bd-08dbedbf2aac"
        },
        {
            "@odata.type": "#NS.RegistrationDTO",
            "registrationId": "b0175d98-9ed8-431d-43be-08dbedbf2aac"
        }
    ]
}
```

**Comment by lenardchristopher** [comment]
Researching this a bit more, I think it is a limitation of AutoMapper as a layer on top of the ORM. As far as I know, `GetQueryAsync` is using `ProjectTo` under the hood. `ProjectTo` produces a Queryable with no underlying knowledge of the data schema and doesn't know about anything beyond the base type.

In the mapping profile, `IncludeBase`/`IncludeAllDerived` only work one way --> exposing the base types mappings to the derived. t would be interesting if their was a way to expose the derived types to the base with attributes similar to `JsonDerivedTypeAttribute`.

Anyways, sounds like an issue for AutoMapper instead of this OData extension repo. Probably good to close, but would be interested to hear any thoughts.

Side-effect: I decided TPH just isn't worth it when working with DTOs. Broke everything up.

**Comment by BlaiseD** [comment]
You might want to include an example to make clear what you think is failing.  At at high level I AutoMapper doesn't have any knowledge of a discriminator - not that I know of.  AutoMapper will map properties between objects whether or not the ORM treats a property as a discriminator.

It sounds like your question is about mapping derived types rather than the ORMs TPH feature.  AutoMapper does support adding derived types to the base mappings. See [this example](https://github.com/BlaiseD/LogicBuilder.Samples/blob/f02595c347251d04428c90a91987ba7d161bb921/Xamarin/Contoso/Contoso.AutoMapperProfiles/DescriptorToOperatorMappingProfile.cs#L408).
