### ISSUE TITLE
Filter on unsigned type for trivially-mapped relation yields InvalidOperationException

### ISSUE THREAD

**Issue by bhood-zorus** [AutoMapper/AutoMapper.Extensions.OData#204]
### Source/destination types

```csharp
// Source: EF entity
public class TestEntity
{
    public int Id { get; set; }
    public ulong UserId { get; set; }
}

// Destination: API model
public class TestModel
{
    public int? Id { get; set; }
    public ulong? UserId { get; set; }
}
```

### Mapping configuration

```csharp
public class TestModelProfile : Profile
{
    public TestModelProfile()
    {
        CreateMap<TestEntity, TestModel>();
    }
}
```

### Version: 4.0.1
.NET 6
AutoMapper.AspNetCore.OData.EFCore 4.0.1
AutoMapper 12.0.1
AutoMapper.Collection 9.0.0
AutoMapper.Extensions.ExpressionMapping 6.0.4
AutoMapper.Extensions.DependencyInjection 12.0.1

### Expected behavior

Results are returned normally

### Actual behavior

```
System.InvalidOperationException: For members of literal types, use IMappingExpression.ForMember() to make the parent property types an exact match. Parent Source Type: System.Nullable`1[System.UInt64], Parent Destination Type: System.UInt64, Full Member Name "Value".
```

### Steps to reproduce

Sample project: https://github.com/bhood-zorus/AutoMapperBugDemo
Send a GET request to `https://localhost:port/api/test?$filter=UserId eq 1`

When the `UserId` property of `TestEntity` and `TestModel` is of type `int` and `int?` (respectively), the API request succeeds. When it's of an unsigned type (`uint`, `ulong`, etc.) the application throws the exception above.

The sample project uses an in-memory database for the sake of providing a simple repro. This behavior is currently being seen with a real-world MySQL database using the Pomelo EF provider. The only way I've been able to reproduce this problem has been to use the `GetQueryAsync` extension method, so I assume this is the appropriate repository to report it in.

**Comment by BlaiseD** [comment]
That exception is thrown [here.](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/blob/fd47b8413a37c76e9bc35bc28f920ca1596421ed/src/AutoMapper.Extensions.ExpressionMapping/XpressionMapperVisitor.cs#L650). Best to reproduce it in that repository.  Consider making the member types match using `ForMember`.
