### ISSUE TITLE
OrderBy is not fully unique

### ISSUE THREAD

**Issue by NetanelPersik** [AutoMapper/AutoMapper.Extensions.OData#221]
### Expected behavior
Queries should contain fully unique OrderBy clause [EF Core Pagination](https://learn.microsoft.com/en-us/ef/core/querying/pagination). 

_For example, if results are ordered only by date, but there can be multiple results with the same date, then results could be skipped when paginating as they're ordered differently across two paginating queries. Ordering by both date and ID (or any other unique property or combination of properties) makes the ordering fully unique and avoids this problem. Note that relational databases do not apply any ordering by default, even on the primary key._

Expected queries to allways contain orderBy PK, with priority to the specified $orderBy (if any), so if one passes:

`/resource?$orderby=type desc`

the expected query should be

```
SELECT *
FROM "TEntitiy" AS "c"
ORDER BY "c"."Type" DESC, "c"."Id" DESC
```

### Actual behavior

When one doesn't pass any `$orderBy`, the expression is added with default OrderBy PK (not sure if this is by EF itself or by the library), but when one passes `/resource?$orderby=type desc` there is no additional orderBy by another unique column.

```
SELECT *
FROM "TEntitiy" AS "c"
ORDER BY "c"."Type" DESC
```

**Comment by BlaiseD** [comment]
I think you're referring to [this call](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/05a00689d8c43ed30f9561dea24cbc6f8ac40868/AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs#L176). 

You're saying:

- Order by PK when no `$orderby` is specified.
- If and an `$orderby` is specified still make order by PK the last `ThenBy` call.

Ok to submit a PR.
