### ISSUE TITLE
It is possible to pass as a parameter or parameterize the class "ODataQuerySettings"?

### ISSUE THREAD

**Issue by JeanGatto** [AutoMapper/AutoMapper.Extensions.OData#43]
The code below works, however I need to return the DTO and not the POCO entities:

` var queryable = this._context.Cities.AsNoTracking().AsQueryable();`
 ` var total = queryable.Count();`
  `var results = queryOptions.ApplyTo(queryable, new ODataQuerySettings() { PageSize = pageSize });`

When I use the AutoMapper.Extensions.OData library, ODataQuerySettings is not supported
` var result = await queryable.GetQueryAsync<CityDTO>(this._mapper, queryOptions);` 

Any suggestion?
Hugs!

**Comment by BlaiseD** [comment]
The [OData repository](https://github.com/OData/WebApi/tree/master/src/Microsoft.AspNetCore.OData) or StackOverflow will probably be more helpful.

We help with bugs/questions about `AutoMapper.Extensions.OData` - as you've pointed out the API does not support `ODataQuerySettings`.
