### ISSUE TITLE
OData metadata became invalid after using this extension.

### ISSUE THREAD

**Issue by matteo-mosca** [AutoMapper/AutoMapper.Extensions.OData#55]
Hi there,
I'm developing an OData service. At first I was using straight database models, and everything was working fine.
Then my client asked me to add projections to custom model and that's how I found your project.
I followed all your recommendations and instructions on how to use it, avoid to use EnableQuery, etc. and it "kinda" works.

If I query the OData endpoints with a REST client like Postman everrything works. But as soon as I try to give the OData feed to any OData enabled client like Power BI or the LinqPad driver I start getting different errors on the $metadata path.

The first problem I encountered was that the clients did not see the metadata document anymore. 404. I tried with postman and this did not work:

`https://localhost/odata/$metadata`

But this worked:

`https://localhost/odata`

So even if it's not clear to me why this happens after adding your extensions, I went around it with a simple rewrite. Now the clients find the document but they report it as an invalid document. This is Power BI error:

> Details: "OData: The feed's metadata document appears to be invalid. Error: A supported MIME type could not be found that matches the content type of the response. None of the supported type(s) 'application/xml' matches the content type 'application/json; odata.metadata=minimal; odata.streaming=true'."

And this is the error I get from the LinqPad driver:

> Error: XmlException - Data at the root level is invalid. Line 1, position 1.

I hope you can help with this, I'm currently stumped.

Thanks.

**Comment by BlaiseD** [comment]
Maybe look at the sample [WebAPI projects](https://github.com/AutoMapper/AutoMapper.Extensions.OData) in the solution and go from there?  (you'll have to open the solution's Configuration Manager and check the build checkboxes - they are turned off to simplify the CI build)

Both of the following work.
http://localhost:16324/$metadata
http://localhost:19583/$metadata

Consider inspecting the results with some client component to help figure out the difference -  like with our [web tests.](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/c5418c619356d4e2072e8e3bb22cf37760ed1d07/Web.Tests/GetTests.cs#L502)

Seems unrelated to the extension.

**Comment by matteo-mosca** [comment]
I will check this out and update the issue, thank you for the feedback.

**Comment by BlaiseD** [comment]
Sounds good.

**Comment by matteo-mosca** [comment]
I tried your WebApi.OData.EFCore project, setting the connectionstring to a new local database on my sqlexpress to be sure everything was in place, and set it as startup project.

Hitting F5 gives this in the browser:

![image](https://user-images.githubusercontent.com/11195767/93519304-5f3f0980-f92e-11ea-8799-a879e2685de2.png)

Database is still pristine, tables are not created so I guess it doesn't even reach the point where it initializes the dbcontext.

Then trying to connect through Power BI I get this:

![image](https://user-images.githubusercontent.com/11195767/93518843-b2648c80-f92d-11ea-8ad8-4c3ccfdcfbb2.png)

I am pointing at the HEAD on the master branch and the only thing I changed is the connectionstring. Do you have any idea about what's going on?

Thanks.

**Comment by BlaiseD** [comment]
I've added two EXEs to help setup the sample web projects.

1. Update the connection strings [here](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/a95984cd5dfa884c633758dd052420f9c14b2489/MigrationTool/MigrationContext.cs#L13) and [here](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/a95984cd5dfa884c633758dd052420f9c14b2489/SeedDatabase/appsettings.json#L3).
2. Run MigrationTool.
3. Run SeedDatabase.

Your issue seems unrelated though.  I would setup break points to figure out why it's blowing up for you.

This forum is really for problems/bugs related to the libraries - see some of the other closed issues.
