### ISSUE TITLE
AutoMapper.AspNetCore.OData.EF6 .NET Core

### ISSUE THREAD

**Issue by jesperowski** [AutoMapper/AutoMapper.Extensions.OData#58]
Will the AutoMapper.AspNetCore.OData.EF6 library appear on nuget in the .NET Standard / .NET Core version? At the moment there is only support for .NETFramework 4.6.1.

**Comment by BlaiseD** [comment]
PRs are welcome.  I think the full framework was required before .Net Core 3.0.

**Comment by jesperowski** [comment]
Strange but it seems like this library already supports .NET Standard. https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/a95984cd5dfa884c633758dd052420f9c14b2489/AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj#L4
Unfortunately for some reason, there is only support for .NETFramework on NuGet.

**Comment by BlaiseD** [comment]
Wrong library. There are [three ](https://github.com/AutoMapper/AutoMapper.Extensions.OData#nuget-package-downloads) in this repo.
