### ISSUE TITLE
paging (skip / top) and expand

### ISSUE THREAD

**Issue by xaviervv** [AutoMapper/AutoMapper.Extensions.OData#6]
Found issue while trying to fix #3 

Paging gets applied twice when EnableQueryAttribute is enabled on the controller / action method. 
Once because of the implementation in the library.
And once somewhere else (client? ServerSide before sending response?)

But without using EnableQueryAttribute expand no longer works. The final result in the controller contains all of the properties for expand; But the navigation is not visible in the final result for odata in the browser (json)

Either need to find a way to force expand results without enablequery, or to block the double paging.

**Comment by xaviervv** [comment]
Possible fix: 
` Request.ODataProperties().SelectExpandClause = options.SelectExpand.SelectExpandClause;`

**Comment by BlaiseD** [comment]
That doesn't sound right. Expand is implemented by `GetIncludes` found in the EFCoreLinqExtensions class - see the unit tests.  Unit tests should be independent of EnableQuery.  I'll follow up later.

**Comment by BlaiseD** [comment]
Ok - I hadn't fully read your notes.   That makes sense.

**Comment by xaviervv** [comment]
I know that there is a method for it; And DB wise, the generated SQL query includes all operations. Even on my controller, I can see all of the navigations. But without EnableQuery, I can't see the navigations by using the url /odata/Roles?$expand=Users. 

I quickly tried again now, on a simple one to many (without a navigation table in between), and got the same issue. No EnableQuery -> no navigation properties. (Again, SQL is generated like I expected, and result in controller contains the navigations)

[Similar issue regarding someone parsing odataoptions on his own, sort of
](https://stackoverflow.com/questions/27535409/expanding-navigation-properties-with-odataqueryoptions
)

I have one question though, both the Count issue, and this issue have similar fixes, modifying Request object. Is it ok to do these modifications in your project? If so, once both fixes are tested locally, I could add new PRs for both count and the extend.

For now I can work around it by doing it in my controller, and not in your project.

PS: the so answers mentioned that EnableQuery and options are mutually exclusive. I didn't know that (I am new to odata). If that is true, perhaps it could be documented in your project as well. For new comers like me, that quickly want to support one or two odata calls to support some filtering. 

So is the following statement correct, that EnableQuery should never be used, when using your project?

**Comment by BlaiseD** [comment]
Thanks for working on this @xaviervv .  Please try the [MyGet build](https://myget.org/feed/automapperdev/package/nuget/AutoMapper.AspNetCore.OData.EFCore).  I think I was able to put everything in the first PR (except for the select ) but let me know if anything looks incorrect.
