### ISSUE TITLE
Support for ODataQuerySettings in GetAsync/Get

### ISSUE THREAD

**Issue by fw2568** [AutoMapper/AutoMapper.Extensions.OData#62]
Hello Blaise,

I have noticed that the `GetAsync` and `Get` method contains a `handleNullPropagation` argument, that is later used to create the `ODataQuerySettings ` in the `LinqExtensions.ToFilterExpression` method. 

However, to configure other options like the PageSize, I think it is better to allow the ODataQuerySettings to be passed directly in both Get methods. 

Something similar was also requested in issue #43 .

I have added a working inplementation here, if you agree I can send you a PR.

Branch:
https://github.com/fw2568/AutoMapper.Extensions.OData/tree/querysettings

Compare with current master:
https://github.com/AutoMapper/AutoMapper.Extensions.OData/compare/master...fw2568:querysettings 

Best Regards,
Frank

**Comment by BlaiseD** [comment]
I agree passing in `ODataQuerySettings` is preferable to `HandleNullPropagationOption`. 

FYI we handle paging through `$top` and `$skip` arguments in the URL  (you've probably seen the [tests](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/cbcb9fd9b11878d14db25c2a13d0d59f6705d36f/AutoMapper.OData.EFCore.Tests/GetQueryTests.cs#L293)).

If you do submit the PR you'll also want to update the tests to replace `HandleNullPropagationOption` with the `ODataQuerySettings` parameter.

Thanks.
