### ISSUE TITLE
Expand and flattened collections

### ISSUE THREAD

**Issue by kakone** [AutoMapper/AutoMapper.Extensions.OData#66]
Hello,

I have an [Order](https://github.com/kakone/AutoMapperTest/blob/main/WebApplication/Order.cs) entity with [lines](https://github.com/kakone/AutoMapperTest/blob/main/WebApplication/OrderLine.cs) that contains a [Product](https://github.com/kakone/AutoMapperTest/blob/main/WebApplication/Product.cs). The [OrderDTO](https://github.com/kakone/AutoMapperTest/blob/main/WebApplication/OrderDTO.cs) have a flattened collection Products with this [mapping](https://github.com/kakone/AutoMapperTest/blob/main/WebApplication/Mappings.cs) :
```csharp
CreateMap<Order, OrderDTO>()
    .ForMember(d => d.Products, o => o.MapFrom(s => s.Lines.Select(l => l.Product)));
```

When I try to expand this Products collection (`/test?$expand=Products`), there is no error but the products contains only null values (a `ThenInclude(l => l.Product)` is missing in the query) :
```json
[{"number":"ORDER_001","products":[null,null]},{"number":"ORDER_002","products":[null]}]
```

Is this kind of scenario supposed to be supported by AutoMapper.Extensions.OData ?

**Comment by BlaiseD** [comment]
Maybe you need a `CreateMap` from Product to ProductDTO.  Looking at the [tests](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/ca09175269cf4a05d41e473dcafae7601fd854b7/AutoMapper.OData.EFCore.Tests/GetQueryTests.cs#L62) might help.

Otherwise post a repro we can run.

**Comment by kakone** [comment]
> Maybe you need a `CreateMap` from Product to ProductDTO.

It's always done [here](https://github.com/kakone/AutoMapperTest/blob/main/WebApplication/Mappings.cs).

> Otherwise post a repro we can run.

https://github.com/kakone/AutoMapperTest/

**Comment by BlaiseD** [comment]
You are correct that's not supported.

You're better off with `GetQueryAsync` because OData will not allow you to use a [flattened member to deduce the navigation property](https://docs.automapper.org/en/stable/Expression-Translation-(UseAsDataSource).html#mapping-flattened-properties-to-navigation-properties) of the data type.   (`test?$expand=Products($expand=Name)`)

In which case your mapping would have been:
```c#
    public class Mappings : Profile
    {
        public Mappings()
        {
            CreateMap<Product, ProductDTO>();

            CreateMap<OrderLine, ProductDTO>()
                .ForMember(dto => dto.Name, opt => opt.MapFrom(x => x.Product.Name));

            CreateMap<Order, OrderDTO>()
                .ForMember(d => d.Products, o => o.MapFrom(s => s.Lines));
        }
    }
```

PRs are welcome.
