### ISSUE TITLE
Query options are ignored in Expand except $select

### ISSUE THREAD

**Issue by hasandogu** [AutoMapper/AutoMapper.Extensions.OData#68]
Thanks for the great work with this great library.

I have already created a [StackOverflow question](https://stackoverflow.com/questions/64568079/invalidoperationexception-with-top-or-skip-in-odata-expand) related with this issue and wanted to also add it here in case it is missed there.

Query options inside the Expand is completely ignored while it partially works (except for $skip and $top) with ProjectTo.

https://localhost:44347/v1/odata/subcategories?$top=2&$expand=products($top=1) is ignored and all nested products are expanded

Here is how we use it with the Queryable Extensions and all the 
```
        [AllowAnonymous, HttpGet]
        public async Task<IActionResult> Get(ODataQueryOptions<ProductSubcategoryDto> options)
        {
             return Ok(await DbContext.ProductSubcategories.GetQueryAsync(Mapper, options));
        }
```

The only option that seems to not be ignored is $select.

Am I doing everything right here? Is there a reason for these query options to be ignored?

We are using EF Core 3.1.9 with Automapper 10.1.1 and AutoMapper.AspNetCore.OData.EFCore 2.0.2.

**Comment by BlaiseD** [comment]
With respect to "all nested products being expanded" you may be missing [ExplicitExpansion](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/ca09175269cf4a05d41e473dcafae7601fd854b7/AutoMapper.OData.EFCore.Tests/Mappings/CoreBuildingMappings.cs#L6) in your configuration.

Other than $select, we support [$filter, $orderby, $top, and $skip](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/ca09175269cf4a05d41e473dcafae7601fd854b7/AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs#L453) for nested collections.

See examples in the [tests](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/ca09175269cf4a05d41e473dcafae7601fd854b7/AutoMapper.OData.EFCore.Tests/GetQueryTests.cs#L553).

We might have a bug if $kip and $top are not working for child collections.   Please post a repro or add a [failing test](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/ca09175269cf4a05d41e473dcafae7601fd854b7/AutoMapper.OData.EFCore.Tests/GetQueryTests.cs#L553).

**Comment by hasandogu** [comment]
Many thanks @BlaiseD  for the fastest response.

I've created a minimal repo with the problem occuring https://github.com/hasandogu/ODataExpandQuery

With that, I have also figured out what the culprit is but don't have a meaningful solution yet.

All the clients of our api are using lower camel case with property names. Therefore, we enabled lower camel case as when building our EDM model through

- builder.EnableLowerCamelCase();


As the expansion expressions are generated the queryable extensions are using the identifier below, which is "subcategory" (not the small first letter as it is generated to be lower camel case due to the call above. It also seems that the only thing that is capitalized correctly is the NavigationSource.

https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/67d530a1b66d2659016c1441df2cacdf67c9f659/AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs#L418

to be assigned as the MemberName as below.

https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/67d530a1b66d2659016c1441df2cacdf67c9f659/AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs#L431

And as the query expression is updated with the Projections for the expansion, it is checking against that with the equality operator. At this point, binding.Member.Name is "Subcategory" when expansion.MemberName is "subcategory", hence the equality statement below returns false and therefore it is added to the list without the queries.

https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/67d530a1b66d2659016c1441df2cacdf67c9f659/AutoMapper.AspNetCore.OData.EFCore/Visitors/ProjectionVisitor.cs#L40

When I disable lower camel case for Odata, all the queries work as expected. Specifically, it is the ProcessReflectedPropertyNames name resolver option that is causing this issue.

- builder.EnableLowerCamelCase(NameResolverOptions.ProcessReflectedPropertyNames);

Unfortunately, this seems to be the only way for OData serialization to be set to use lower camel case for property names and we need it. I am not sure what the best way to go about the equality statement above. Are these bindings or checks against them supposed to be case sensitive?

If case sensitive, is there a way for us to perhaps set the binding names to be lower camel case through a flag as well? Or even force case insensitive checks here.

**Comment by BlaiseD** [comment]
You are correct.  `string.Compare(binding.Member.Name, expansion.MemberName, true) == 0` should work here.

A case insensitive check is the best practice e.g. member names may get passed in from JavaScript - I'm guessing that is the case with your client code.

I have similar code in [another project](https://github.com/BlaiseD/LogicBuilder.DataComponents/blob/46c335c5be92a9354f72787732b26aedb2330188/LogicBuilder.EntityFrameworkCore.SqlServer/Visitors/ChildCollectionVisitor.cs#L43) for the same reason.

A PR is welcome.

**Comment by hasandogu** [comment]
Member names seem to be all normalized to their Pascal cases, which is what we have for the DTOs and the Entities. I'll add the case insensitive checks and submit a PR.

Do you think we should also add enable lower camel case with the EDM by default?
