### ISSUE TITLE
[Question] How to enable OData paging? 

### ISSUE THREAD

**Issue by DanielGlos** [AutoMapper/AutoMapper.Extensions.OData#79]
As the documentation says you are not supposed to use [EnableQuery] attribute when using GetQueryAsync method. My question is how can we enable OData paging which is usually done by setting PageSize e.g. [EnableQuery(PageSize=10)].
Also when in my Startup class I set MaxTop like this:
`endpoints.Select().Expand().Filter().OrderBy().Count().MaxTop(10);`
It is ignored when [EnableQuery] attribute is not present in the controller.

Are there any plans on allowing [EnableQuery] with GetQueryAsync?

**Comment by BlaiseD** [comment]
No plans to allow `[EnableQuery]` - it ends up duplicating the logic.

I would recommend a new `ODataSettings` class to be a child property of  [QuerySettings](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/f3a730314bb7c0f14ff7a9f2bef3bd09b1f85f42/AutoMapper.AspNetCore.OData.EFCore/QuerySettings.cs#L8) if you need to set the page size on the server - [plus logic to define precedence over](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/f3a730314bb7c0f14ff7a9f2bef3bd09b1f85f42/AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs#L83) `$top`.

`QuerySettings.HandleNullPropagationOption` can be moved to the new class - I think it's only been there in preview.

**Comment by dasariramacharan** [comment]
@BlaiseD 
           Any plans to implement ODATA Paging support?

**Comment by BlaiseD** [comment]
No plans to implement server-side paging but PRs are welcome.

You'll have to add a `PageSize` property to [ODataSettings](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/6224f587b1f61a4a750593f0945a2824496bea31/WebAPI.OData.EFCore/Controllers/OpsTenantController.cs#L28) and give it precedence over `$top` when we build the expression.
