### ISSUE TITLE
How to enable odata @nextlink 

### ISSUE THREAD

**Issue by dasariramacharan** [AutoMapper/AutoMapper.Extensions.OData#82]
@nextlink automatically appears in the response when using 'EnableQuery' (like shown below) which we are not supposed to use when using this extension.

`[EnableQuery(PageSize=5)]  
public IHttpActionResult Get() `

  Could you please suggest how to enable @nextlink automatically in the response while using this library to enable server driven Paging.

**Comment by BlaiseD** [comment]
NextLink can be applied to the response if you implement server-side paging e.g. `options.Request.ODataFeature().NextLink = someUri`.
