### ISSUE TITLE
Joining table and expand

### ISSUE THREAD

**Issue by xaviervv** [AutoMapper/AutoMapper.Extensions.OData#9]
My profile
```
public RolesProfile()
        {
            CreateMap<ApplicationRole, RoleGridRow>()
                .ForMember(d => d.Users, opt =>
                {
                    opt.AllowNull();
                    opt.ExplicitExpansion();
                    opt.MapFrom(s => s.UserRoles);
                });

            CreateMap<ApplicationUserRole, User>()
                .ForMember(d => d.Id, o => o.MapFrom(s => s.User.Id))
                .ForMember(d => d.Name, o => o.MapFrom(s => s.User.Name.FullName));

            CreateMap<ApplicationUser, User>()
                .ForMember(d => d.Name, o => o.MapFrom(s => s.Name.FullName));
        }

```
Domain: Role -> UserRoles (id and object both ways) -> User
User -> UserRoles -> Role

DTO: Role -> Users (name & id)
User -> Roles (Name & id)

pretty much as my example repo from before

Now when I do something like expand `/odata/role?$expand=Users`, the generated sql only creates an inner join for the joining table (UserRoles), but never another join from userRoles to user (which means I can't get user info besides ids)
this is with using: `_context.Roles.AsNoTracking().GetAsync(_mapper, request.ODataOptions);`

If I would add the both includes here myself, then I get the results, but the select no longer matches the dto

If I change the profile to 

```
ForMember(d => d.Users, opt =>
                {
                    opt.AllowNull();
                    opt.ExplicitExpansion();
                    opt.MapFrom(s => s.UserRoles.Select(x => x.User));
                });
```
I get some collection null error

**Comment by xaviervv** [comment]
Small update

GetAsync without includes => user.name not populated by odata
GetAsync with includes => select statements not modified in accordance with viewmodel

GetQueryAsync and calling.tolist with includes => no issues
GetQueryAsync and calling .toList without includes => no issues

So I'll just change my calls to GetQueryAsync, but you may still want to test this / check this out. 
For me it doesn't matter much weither I get a list, or call to list myself.

But the different behavior between the two is rather weird. Unless I was using it wrong to start with.

**Comment by BlaiseD** [comment]
There are multiple examples of expansions `Entity.ChildEntity.GrandChildEntity` in the test cases - all using `GetAsync`.

The OData query should look something this:
`"/opstenant?$top=5&$expand=Buildings($expand=Builder($expand=City))&$filter=Name ne 'One'&$orderby=Name desc"`

On the difference between `GetQueryAsync` vs `GetAsync` you're seeing the difference between `IMapper.Map` and `IMapper.ProjectTo`.

If the tests don't help please post a sample we can run and see fail (actual results, expected results etc.).

**Comment by xaviervv** [comment]
I will test it again later, to be sure. Really need to continue on the projects (deadlines)
Everything works with my fixes applied locally and GetQuery, so I’ll check it out later, when I have a bit more time

In my example Entity = User, Child = UserRole, GrandChild = Role
DTO is: User with a collection of Roles (Entity with a collection of GrandChildren)
Without automapper => Entity.Children.Select(x => x.GrandChild)

But the thing is, expand only works on DTO, so I can only expand to one level: odata/roles?$expand=Users
I know that without mapping, and working straight on the entities I can do: odata/roles?$expand=Users($expand=UserRoles($exand=Role))

I will update my sample repo when I have some more time again.

**Comment by BlaiseD** [comment]
Check out [Mapping flattened properties to navigation properties](https://docs.automapper.org/en/stable/Expression-Translation-(UseAsDataSource).html) -  what you're saying isn't quite clear without actual classes but I believe that is what you're referring to.  `IMapper.MapExpressionAsInclude()` which you'll find in the project will take the flattened property (member expression) and map it to a member expression for the declaring parent object in the domain object.

**Comment by BlaiseD** [comment]
Should be working using QueryableExtensions.GetQueryAsync in [version 1.0.2-preview04](https://www.nuget.org/packages/AutoMapper.AspNetCore.OData.EFCore/1.0.2-preview04). See the [unit tests](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/master/AutoMapper.OData.EFCore.Tests/GetQuerySelectTests.cs).
