### ISSUE TITLE
Breaking change when upgraded to Microsoft.AspNetCore.OData v8.0.0-preview3

### ISSUE THREAD

**Issue by DanielGlos** [AutoMapper/AutoMapper.Extensions.OData#90]
This is a follow-up issue to my previous question #89. When I upgrade to package mentioned in title the namespace for ODataQueryOptions<TEntity> class changes from Microsoft.AspNet.OData.Query to Microsoft.AspNetCore.OData.Query but AutoMapper.AspNet.OData.QueryableExtensions explicitly says that ODataQueryOptions must come from Microsoft.AspNet.OData.Query. It would be nice if you could release a preview package with this change.

**Comment by BlaiseD** [comment]
That was the namespace in version 7.  We should  wait until v8 is out of preview before updating the libraries which reference it: `AutoMapper.AspNetCore.OData.EF6` and `AutoMapper.AspNetCore.OData.EFCore`. 

Is there a new feature you're trying to use?

**Comment by DanielGlos** [comment]
No, not any special functionality it's just I want to update my project to NET 5 and for that I need to update Microsoft.AspNetCore.OData because of another dependency I have and then this conflict occures.

**Comment by BlaiseD** [comment]
So you have a dependency using the preview.

If you PR the Microsoft.AspNetCore.OData.v8 branch, we can release the preview separately from that branch.   Better to stay away from multiple release branches typically.

**Comment by BlaiseD** [comment]
Version [2.2.0-preview.1](https://www.nuget.org/packages/AutoMapper.AspNetCore.OData.EF6/2.2.0-preview.1) references Microsoft.AspNetCore.OData v8.0.0-rc.
