### ISSUE TITLE
$skip is not applied when $orderby is not defined

### ISSUE THREAD

**Issue by darjanbogdan** [AutoMapper/AutoMapper.Extensions.OData#94]
I've encountered issue when using standalone $skip parameter, for example `corebuilding?$skip=2`

I think problem lies in `GetQueryableMethod` method:

```
if (orderByClause == null)
{
    return Expression.Call
    (
        expression.Type.IsIQueryable() ? typeof(Queryable) : typeof(Enumerable),
        "Take",
        new[] { type },
        expression,
        Expression.Constant(top.Value)
    );;
}
```

So, if `OrderByClause` is not defined, only `Take` expression is going to be returned, without applying `Skip` expression. 

Before starting with the fix, could you tell me if this is actually a bug, or intended behavior. To me, it looks like the bug.

**Comment by BlaiseD** [comment]
It's by design.  I think EF6 would throw an exception using `Skip` without `OrderBy`.  It's also recommended with [EF Core](https://stackoverflow.com/questions/37683555/skip-and-take-in-entity-framework-core).

Maybe it's a good idea to throw an `InvalidOperationException` if `Skip` is provided without `OrderBy` - so it's clear the logic is intended.

**Comment by darjanbogdan** [comment]
I agree with your point call to `GenerateStableOrder` is also skipped, even with `EnableStableOrdering=true` which is default. The reason for that is because `ApplyTo` is called only if $filter is defined.

default behavior of MS OData lib:
https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/Query/ODataQueryOptions.cs#L380

This basically means breaking change from the client's perspective, any thoughts?

**Comment by BlaiseD** [comment]
> Note: OData spec says that service MUST impose a stable sort ordering, if $skip is included.

I think that is what we're doing by not allowing `$skip` without `$orderby`.  I won't characterize the non-call to `GenerateStableOrder` as being skipped.  It's a feature this library does not have. 

At some point we should get rid of the [ApplyTo here](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/de609830a04c003cb5495d5358a163d6f697c4e0/AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs#L33) is favor of just `return (Expression<Func<T, bool>>)filterOption.FilterClause.GetFilterExpression(typeof(T));`.  I don't think it's quite ready.

That way we're generating all our own expressions.

We can add new features like `GenerateStableOrder` to [QuerySettings](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/master/AutoMapper.AspNetCore.OData.EFCore/QuerySettings.cs) and implement them.

Where do you see breaking changes?

**Comment by darjanbogdan** [comment]
Since the library depends on _Microsoft.AspNetCore.OData_ package and uses it to build part of the expression tree I was under the impression that stable ordering behavior will remain unchanged (i.e. follow the _base_ library). 

The complete paragraph in the spec states the following:
> If no unique ordering is imposed through an $orderby query option, the service MUST impose a stable ordering across requests that include $skip.

So, current behavior as well as throwing an exception could be considered a violation of the spec. But I guess we just have a different view on the topic. 

To conclude, I'm happy to help to implement that "feature", but to avoid a lengthy PR process it would be awesome if you can provide some implementation guidelines. For example, I was thinking to expose `EnableStableOrdering` prop on `ODataOptions`, and still rely on `options.GenerateStableOrder` method to generate `OrderByClause` if not present already.

**Comment by BlaiseD** [comment]
`EnableStableOrdering` is set on the server correct (using `EnableQuery`)?  Did you mean [ODataSettings](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/de609830a04c003cb5495d5358a163d6f697c4e0/AutoMapper.AspNetCore.OData.EFCore/ODataSettings.cs#L8)?

Getting the `OrderByQueryOption` from `options.GenerateStableOrder()` works.

**Comment by darjanbogdan** [comment]
`EnableStableOrdering` is set on the server via [ODataQuerySettings](https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/Query/ODataQuerySettings.cs#L61) it is `true` by default (I'm not sure if it's affected by `EnableQuery` attribute, but that's not that important). 

So, I was just thinking to reuse the same terminology and indeed extend `ODataSettings` with our own `EnableStableOrdering` property.

**Comment by BlaiseD** [comment]
sounds good.

**Comment by DanielGlos** [comment]
Hello,

same situation as @jacquesroesen mentioned @odata.nextLink is not usable with current implementation which definitely is spec violation. Is anyone working on this at the moment?

**Comment by BlaiseD** [comment]
I know I'm not.  PRs are welcome.

**Comment by darjanbogdan** [comment]
Hi @DanielGlos, I also don't work on it, didn't have time to properly implement it back then.

What I did instead is a hack which is acceptable in my case, snippet example:

```csharp
private static readonly PropertyInfo _orderByPropertyInfo = typeof(ODataQueryOptions).GetProperty("OrderBy");
public static void EnsureStableOrdering(this ODataQueryOptions queryOptions)
{
    if (queryOptions.OrderBy is null)
    {
        _orderByPropertyInfo.SetValue(queryOptions, queryOptions.GenerateStableOrder());
    }
}
```

`GenerateStableOrder()` is a method from the _Microsoft.AspNet.OData.Query_ library and similarly should be used here in my opinion.

**Comment by DanielGlos** [comment]
@darjanbogdan neat, thank you! :)

**Comment by wbuck** [comment]
I'm assuming that `skip` without a corresponding `orderby` should also work for navigation collections as well? 

So, a query such as `/CategoryModel?$expand=Products($skip=1;$select=ProductName)` should return an ordered collection of product name's minus the first result?

I'm trying to determine if this is a valid use case.

**Comment by BlaiseD** [comment]
Yes - I don't see why not - if we're going to allow it at the root then it should be ok for the nested collections also.

**Comment by wbuck** [comment]
I'm also curious about `Take`. Currently, if an order was _not_ specified but `Take` was, then the following method call expression is created:

    return Expression.Call
    (
        expression.Type.IsIQueryable() ? typeof(Queryable) : typeof(Enumerable),
        "Take",
        new[] { type },
        expression,
        Expression.Constant(top.Value)
     );

I believe in this case, a default order should be created for this case as well.

So far, implementing this at root is trivial, but for nested collections it's a bit more involved as there are no `ODataQueryOptions` on which to call `GenerateStableOrder`.

My thought here is to mimic `GenerateStableOrder`, which means determining which properties can be used to generate a stable order. Right now I'm just taking a look at what's being done [here](https://github.com/OData/WebApi/blob/46a0d5a8ef34938066e65c0afc4fa5ca956f971e/src/Microsoft.AspNet.OData.Shared/Query/ODataQueryOptions.cs#L605).

**Comment by wbuck** [comment]
Yeah, so currently I'm generating a default order for the following cases:

1. `orderby` is `null` but `skip` is not
2. `orderby` is `null` but `top` is not
3. `orderby` is `null` but both `top` and `skip` are not

I agree with you about using the same method for generating an order, keep things consistent.
I'll start on creating such a method and go from there.

**Comment by wbuck** [comment]
OK, just need to write a bunch of unit tests. Hoping to have a PR in for this before the end of the week (assuming I don't run in to a show stopper of course)
